// generated by gengoos.go using 'go generate'

package sys

const TheGoarch = `amd64`

const Goarch386 = 0
const GoarchAmd64 = 1
const GoarchAmd64p32 = 0
const GoarchArm = 0
const GoarchArm64 = 0
const GoarchMips64 = 0
const GoarchMips64le = 0
const GoarchPpc64 = 0
const GoarchPpc64le = 0
